### ISSUE TITLE
Front end email sending won't send body

### ISSUE THREAD

**Issue by aj1215** [objectivehtml/Postmaster-for-Craft-CMS#10]
I cannot get a front end email to send the 'body' portion of the message, although everything else gets sent. Here is my setup for the form:
```
<form action="" method="post">
    <input type="hidden" name="action" value="postmaster/forms/send">
    <input type="hidden" name="redirect" value="/dashboard">
    <input type="hidden" name="fromEmail" value="{{ currentUser.email }}">
    <input type="hidden" name="fromName" value="Coach {{ currentUser.firstName }}">
    <input type="hidden" name="toEmail" value="test@test.com">

    <p>
        <label for="subject">Subject</label><br>
        <input type="text" id="subject" name="subject" value="{{ email.subject }}" />
        {% if email.getError('subject') %}
        <label for="subject">{{ email.getError('subject') }}</label>
        {% endif %}
    </p>

    <p>
        <label for="body">Message</label><br>
        <textarea type="text" id="body" name="body">{{ email.body }}</textarea>
        {% if email.getError('body') %}
        <label for="body">{{ email.getError('body') }}</label>
        {% endif %}
    </p>

    <button>Send</button>

</form>
```
And my parcel setup:
![screen shot 2015-01-31 at 12 10 41 pm](https://cloud.githubusercontent.com/assets/36492/5989601/4a8f80ce-a942-11e4-91ab-9ef5e385f89f.png)
![screen shot 2015-01-31 at 12 10 51 pm](https://cloud.githubusercontent.com/assets/36492/5989600/48e48436-a942-11e4-9f59-1c6a83896139.png)
![screen shot 2015-01-31 at 12 11 05 pm](https://cloud.githubusercontent.com/assets/36492/5989594/40aeae04-a942-11e4-8972-e3d4f0ec5e58.png)
![screen shot 2015-01-31 at 12 11 01 pm](https://cloud.githubusercontent.com/assets/36492/5989598/443d787a-a942-11e4-9cfc-7f6fd1a0fc06.png)
![screen shot 2015-01-31 at 12 10 57 pm](https://cloud.githubusercontent.com/assets/36492/5989599/4681f5de-a942-11e4-93f2-67dd072bbf6e.png)

**Comment by objectivehtml** [comment]
Change this:
`<textarea type="text" id="body" name="body">{{ email.body }}</textarea>`

To:
`<textarea type="text" id="message" name="message">{{ email.message }}</textarea>`

**Comment by aj1215** [comment]
Throws an error:

![screen shot 2015-01-31 at 12 16 42 pm](https://cloud.githubusercontent.com/assets/36492/5989642/116569fc-a943-11e4-9f86-c8ca20b68b30.png)

**Comment by objectivehtml** [comment]
My mistake, try this:

`<textarea type="text" id="message" name="message">{{ email.body }}</textarea>`

**Comment by aj1215** [comment]
Hmm. Not it won't submit because of this error.

2015/01/31 20:19:00 [warning] [application]
Craft\Postmaster_EmailFormModel->body failed validation: Body cannot be
blank.

On Sat, Jan 31, 2015 at 12:18 PM, Justin Kimbrell <notifications@github.com>
wrote:

> My mistake, try this:
>
> <textarea type="text" id="message" name="message">{{ email.body
> }}</textarea>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/objectivehtml/Postmaster-for-Craft-CMS/issues/10#issuecomment-72334429>
> .
>



-- 
-
AJ

**Comment by objectivehtml** [comment]
Hm.. something isn't right. I am working on some Postmaster stuff now actually. I will take a look at this in a bit and try to find the cause.

**Comment by objectivehtml** [comment]
Sorry for the delay on this. Can you give this a shot now. Just download the master branch to get the latest files, change "message" back to "body".

You can now define an html or plain text template to output your content dynamically. If you leave the template option blank, the raw content submitted by the user will be used. This is working for me locally. Let me know if you are still having issues.
