### ISSUE TITLE
Fatal error: Class 'Carbon\Carbon' not found

### ISSUE THREAD

**Issue by ctigelaar** [objectivehtml/Postmaster-for-Craft-CMS#22]
I would like to try the functionality of Postmaster for a current project, but I'm getting an error during installation. I followed the simple Installation guide from the wiki.

`Fatal error: Class 'Carbon\Carbon' not found in /craft/plugins/postmaster/core/parcel_schedules/SendDateParcelSchedule.php on line 17`

After the installation my Craft installation doesn't work anymore. I'm guessing it has something to do with Composer, I do use that for other Craft plugins. I already tried removing the `vendor` directory inside the `plugins/postmaster` directory and ran both `composer install` and `composer update`, but without any luck. Can you help me or is this a bug?

**Comment by ctigelaar** [comment]
Solved it for now. The problem does not occur when I rename my `vendor` folder in my root to some random value. So it seems to be a (local?) problem with the Composer autoloader.

**Comment by ctigelaar** [comment]
Issue was caused by my own autoloader, when I run my own composer with the `--no-autoloader` flag everything works just fine. Has nothing to do with Postmaster I think. Closing it.

**Comment by kabircse** [comment]
It works with global namespace to my view.blade.php as

      {{ \Carbon\Carbon::parse($row->posted_at)->diffForHumans() }}
