### ISSUE TITLE
Getting error using mailchimp

### ISSUE THREAD

**Issue by keithmancuso** [objectivehtml/Postmaster-for-Craft-CMS#4]
Im trying to have a parcel send to a mailchimp list and i keep getting

Invalid MailChimp List ID: Array

error.

When i put in my api key i get a list of my lists and i checked it and i also tried just inputting the list id but same error for both?

Any ideas?

**Comment by keithmancuso** [comment]
So it looks like the issue is that the listsIds is an array... in my database im seeing this

"listIds":["","myListId"]

where the first one is always blank for some reason

so im able to get it to work if i change this on line 14 of the Postmaster_MailchimpCampaignModel

'list_id' => $this->listId[1],

but doesnt feel right?

**Comment by objectivehtml** [comment]
No that's not right. I will fix this soon as I get a chance. The empty index is a long explanation but that is a result of some Craft stuff.

**Comment by objectivehtml** [comment]
This should be fixed now. Download the master branch and give it a shot and let me know if you are still having issues. This was a result of recent changes I made for another user for CampaignMonitor. I made the same updates to MC but I must have missed this bug.
