### ISSUE TITLE
Adding content to Frontend emails

### ISSUE THREAD

**Issue by engram-design** [objectivehtml/Postmaster-for-Craft-CMS#9]
It's likely I'm missing something fundamental here, but after setting everything up correctly to finally get emails being sent when users submit a form, the email is blank. The subject, name and standard stuff works, but non of my other fields are being included.

Should these be specified somewhere?

```
            <form method="post" class="form-horizontal group-border-dashed" action="">
                {% set email = craft.postmaster.email() %}
                <input type="hidden" name="action" value="postmaster/forms/send">
                <input type="hidden" name="redirect" value="/bookings/new">
                
                <input type="hidden" name="toEmail" value="web@domain.com.au" />
                <input type="hidden" name="toName" value="Admin" />
                <input type="hidden" name="fromEmail" value="{{ currentUser.email }}" />
                <input type="hidden" name="fromName" value="{{ currentUser.fullName }}" />
                <input type="hidden" name="cc" value="{{ currentUser.email }}" />
                <input type="hidden" name="bcc" value="{{ currentUser.email }}" />
                <input type="hidden" name="replyTo" value="{{ currentUser.email }}" />
                <input type="hidden" name="subject" value="New Booking Request" />
                <input type="hidden" name="body" value="Test" />

                <input type="text" name="booking_type" />
                <input type="text" name="location" />
                <input type="text" name="property_size" />
                <input type="text" name="occupancy" />
                <input type="text" name="locality" />

**Comment by objectivehtml** [comment]
In the current iteration, this isn't possible with the front-end email parcel type. It requires you pass a "message" field with the message you want to send. This is the email template. I did this so that people didn't have to create an email template for this specific feature.

What you are really looking for is a more advanced way to send and parse emails from the front-end but also use a form to submit the information dynamically. The example below should be possible with a couple changes. The main thing I can thing that would be an issue would be form validation. Somehow you need to validate the email model before it sent in the event the user leaves a field blank. See if you can get this work and if not I will take a closer look at building an example for this.

https://github.com/objectivehtml/Postmaster-for-Craft-CMS/wiki/Send-Messages-from-Templates

**Comment by engram-design** [comment]
I did see that and thought that looked like the next option to try - that makes sense.

However, getting an error using it simply:

```
{% set request = {
    service: 'craft',
    settings: {
        toName: 'Some Name',
        toEmail: 'test@test.com',
        fromName: 'From Name',
        fromEmail: 'test@test.com',
        replyTo: 'test@test.com',
        cc: 'test@test.com',
        bcc: 'test@test.com',
        subject: 'Some subject...',
    },
    sendDate: '2015-01-01 12:00:00'
} %}

{% set response = craft.postmaster.send(request, {
    'someVar': 'Some Value',
}) %}
```

```
Fatal error: Cannot use object of type Carbon\Carbon as array in /public_html/bookings/craft/plugins/postmaster/variables/PostmasterVariable.php on line 28
```

**Comment by objectivehtml** [comment]
Are you using the latest build? I am not getting that issue locally. In the top the `PostmasterVariables` class you can see I have `use Carbon\Carbon`, which should fix that issue. See if you have that code at the top of your file.

**Comment by objectivehtml** [comment]
You have to be using a different build than me, because that is on line 25 on my file.

**Comment by engram-design** [comment]
I'm using the same as in the current master - cloned last night. And line 28 being ```$settingsModel = new $settings['settingsModel']($settings['settings']);```

Troubleshooting with the following code seems to show that the settings are getting stripped out, causing the error.

```
		$settings = array_merge($defaultSettings, $settings);

		var_dump($settings);

		if($settings['sendDate'])
		{
			$settings = Carbon::parse($settings['sendDate'], craft()->getTimezone());
		}

		var_dump($settings);
```

```
Array
(
    [service] => craft
    [serviceSettings] => Array
        (
        )

    [settings] => Array
        (
            [toName] => Some Name
            [toEmail] => test@test.com
            [fromName] => From Name
            [fromEmail] => test@test.com
            [replyTo] => test@test.com
            [cc] => test@test.com
            [bcc] => test@test.com
            [subject] => Some subject...
        )

    [settingsModel] => Craft\Postmaster_EmailModel
    [data] => Array
        (
        )

    [senderId] => 
    [sendDate] => 2015-01-01 12:00:00
    [queueId] => 
)
```

```
Carbon\Carbon Object
(
    [date] => 2015-01-01 12:00:00.000000
    [timezone_type] => 3
    [timezone] => UTC
)
```

**Comment by engram-design** [comment]
Should line 28 be:

```
$settings['sendDate'] = Carbon::parse($settings['sendDate'], craft()->getTimezone());
```

**Comment by objectivehtml** [comment]
Thanks for help with this issue. That is indeed the proper fix.
